// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqxuhenmqnjcbznacjzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxeHVoZW5tcW5qY2J6bmFjanprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3OTQ0NTgsImV4cCI6MjA1NzM3MDQ1OH0.6pm5Lh_WhmhgpIW_-8tt8slr70XExdL1GPjiQeFtNs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);